name: mineru
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.12.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==16.0.1
      - beautifulsoup4==4.14.3
      - blake3==1.0.8
      - boto3==1.42.17
      - botocore==1.42.17
      - brotli==1.2.0
      - cachetools==6.2.4
      - cbor2==5.7.1
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - cobble==0.1.4
      - coloredlogs==15.0.1
      - colorlog==6.10.1
      - compressed-tensors==0.11.0
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cssselect2==0.8.0
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - deprecated==1.3.1
      - depyf==0.19.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - doclayout-yolo==0.0.4
      - einops==0.8.1
      - email-validator==2.3.0
      - exceptiongroup==1.3.1
      - fast-langdetect==0.2.5
      - fastapi==0.128.0
      - fastapi-cli==0.0.20
      - fastapi-cloud-cli==0.8.0
      - fastar==0.8.0
      - fastrlock==0.8.3
      - fasttext-predict==0.9.2.4
      - ffmpy==1.0.0
      - filelock==3.20.1
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - gguf==0.17.1
      - gradio==5.49.1
      - gradio-client==1.13.3
      - gradio-pdf==0.0.22
      - greenlet==3.3.0
      - groovy==0.1.2
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-retries==0.4.5
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - imageio==2.37.2
      - img2pdf==0.6.3
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.12.0
      - jmespath==1.0.1
      - json-repair==0.54.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - lark==1.2.2
      - lazy-loader==0.4
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - lxml==6.0.2
      - magika==1.0.1
      - mammoth==1.11.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markdownify==1.2.2
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mineru==2.6.8
      - mineru-vl-utils==0.1.19.1
      - mistral-common==1.8.8
      - modelscope==1.33.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - onnxruntime==1.23.2
      - openai==2.14.0
      - openai-harmony==0.0.8
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - orjson==3.11.5
      - outlines-core==0.2.11
      - packaging==25.0
      - pandas==2.3.3
      - partial-json-parser==0.2.1.1.post7
      - pdfminer-six==20250506
      - pdftext==0.6.3
      - pikepdf==10.1.0
      - pillow==11.3.0
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.2.0
      - py-cpuinfo==9.0.0
      - pybase64==1.4.3
      - pyclipper==1.4.0
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.6
      - pydantic-settings==2.11.0
      - pydub==0.25.1
      - pydyf==0.12.1
      - pygments==2.19.2
      - pymilvus==2.6.5
      - pyparsing==3.3.1
      - pypdf==6.5.0
      - pypdfium2==4.30.0
      - pyphen==0.17.2
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qwen-vl-utils==0.0.14
      - ray==2.53.0
      - referencing==0.37.0
      - regex==2025.11.3
      - reportlab==4.4.7
      - requests==2.32.5
      - rich==14.2.0
      - rich-toolkit==0.17.1
      - rignore==0.7.6
      - robust-downloader==0.0.2
      - rpds-py==0.30.0
      - ruff==0.14.10
      - s3transfer==0.16.0
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentence-transformers==5.2.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.48.0
      - setproctitle==1.3.7
      - shapely==2.1.2
      - shellingham==1.5.4
      - simsimd==6.5.12
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.8.1
      - soxr==1.0.0
      - sqlalchemy==2.0.45
      - starlette==0.50.0
      - stringzilla==4.6.0
      - sympy==1.14.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.12.0
      - tinycss2==1.5.1
      - tinyhtml5==2.0.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.4.0
      - typer==0.21.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - ultralytics==8.3.241
      - ultralytics-thop==2.0.18
      - urllib3==2.6.2
      - uv==0.9.18
      - uvicorn==0.24.0
      - uvloop==0.22.1
      - vllm==0.11.0
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - weasyprint==67.0
      - webencodings==0.5.1
      - websockets==15.0.1
      - wrapt==2.0.1
      - xformers==0.0.32.post1
      - xgrammar==0.1.25
      - yarl==1.22.0
      - zopfli==0.4.0
prefix: /data/songbinbin/minicoda/envs/mineru
